### ISSUE TITLE
Javascript koji generise autore i clanke na osnovu lokalnih fajlova

### ISSUE THREAD

**Issue by igr** [HeapSpace/heapcon#9]
Treba izgenerisati:

+ markdown po speakeru (dodaj i frontmatter!)
+ sliku spikera
+ markdown po talku (dodaj i frontmatter!)

Ako se sve izgeneriše kako treba, trebalo bi template od prošle godine radi.

Dat je primer jednog talka:

![image](https://user-images.githubusercontent.com/2280001/53699463-c5197e00-3de8-11e9-989a-e15494fd1ecc.png)

**Comment by nikolalsvk** [comment]
Je l ovaj issue rešen ovim komitom možda? :) https://github.com/HeapSpace/heapcon/commit/36784f1c52bf99e31c67953445e765b0a0ecedd6#diff-1578c58a761c0846adb0e788c860a12bR86

**Comment by igr** [comment]
Izgleda :)
